name: project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  get: ^4.6.5
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  google_fonts: ^4.0.4
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  flutter_otp_text_field: ^1.1.0+2
  line_awesome_flutter: ^2.0.0
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  flutter_image_compress: ^2.0.3
  http: ^0.13.6
  shared_preferences: ^2.1.2
  intl: ^0.18.1
  awesome_dialog: ^3.1.0
  image_card: ^0.0.4
  percent_indicator: ^4.2.3
  persistent_bottom_nav_bar: ^5.0.2
  fan_floating_menu: ^0.0.1
  carousel_slider: ^4.2.1
  flutter_slidable: ^3.0.0
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    # - images/logo1.png
    - images/logo2.png
    - images/iconprofile.png
    - images/splashimage.png
    - images/img2.png
    - images/img4.png
    - images/img5.png
    - images/img7.png
    - images/img8.png
    - images/img31.png
    - images/img23a.png
    - images/img34.png
    - images/img35.png
    - images/img36.png
    - images/img37.png
    - images/img38.png
    - images/img39.png
    - images/img27.png
    - images/img15.png
    - images/img16.png
    - images/img40.png
    - images/img41.png
    - images/img28.png
    - images/testimge.png
    - images/folder.png

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
